sudo apt install -y \
    autoconf \
    basez \
    bazel-bootstrap \
    bcc \
    bear \
    bison \
    bpftrace \
    check \
    chrpath \
    clang \
    clang-format \
    clang-format-15 \
    cmake \
    curl \
    debhelper \
    devscripts \
    docker-buildx \
    docker-compose \
    emacs \
    ethtool \
    flatpak \
    flex \
    g++ \
    gcc \
    gcc-12 \
    g++-12 \
    gdb \
    graphviz \
    jq \
    jshon \
    lcov \
    ldap-utils \
    libc-ares2 \
    libtool \
    linux-cloud-tools-6.5.0-35-generic \
    linux-cloud-tools-generic \
    linux-tools-6.5.0-35-generic \
    linux-tools-generic \
    llvm \
    locales \
    mercurial \
    net-tools \
    openssl \
    pkgconf \
    quilt \
    tmux \
    vim \
    wireshark-qt \
    wrk \
    libipset-dev \
    libjson-perl \
    liblua5.2-0 \
    libnl-route-3-200 \
    libqt6core5compat6 \
    libqt6multimedia6 \
    libsmi2ldbl \
    libsnappy1v5 \
    libstdc++6 \
    libtap-formatter-junit-perl \
    libtest-hexstring-perl \
    python3-dev \
    python3-dns \
    python3-dnspython \
    python3-iso8601 \
    python3-jedi \
    python3-markdown \
    libacl1-dev \
    libaio-dev \
    libarchive-dev \
    libbpf-dev \
    libc6-dev-i386 \
    libclang-14-dev \
    libcppunit-dev \
    libdbus-1-dev \
    libelf-dev \
    libgeoip-dev \
    libghc-regex-pcre-dev \
    libgnutls28-dev \
    libgpgme11-dev \
    libjansson-dev \
    libldap2-dev \
    liblmdb-dev \
    libminizip-dev \
    libmnl-dev \
    libpam0g-dev \
    libparse-yapp-perl \
    libpcre3-dev \
    libpopt-dev \
    libspeexdsp-dev \
    libssl-dev \
    libxslt1-dev \
    qt6-base-dev \
    zlib1g-dev
