sudo apt install -y \
    git \
    tmux \
    gcc \
    sudo \
    python \
    python2 \
    python2-dev \
    python3 \
    python3-dev \
    python3-dns \
    python3-dnspython \
    python3-jedi \
    python3-markdown \
    apt-file \
    aptitude \
    build-essential \
    ncurses-term \
    libncurses-dev \
    llvm \
    clang \
    libclang-11-dev \
    zlib1g-dev \
    cmake \
    locales \
    pkg-config \
    xsltproc \
    flex \
    bison \
    libgnutls28-dev \
    liblmdb-dev \
    libgpgme11-dev \
    libparse-yapp-perl \
    libjansson-dev \
    libarchive-dev \
    libacl1-dev \
    libldap2-dev \
    libpam0g-dev \
    libdbus-1-dev \
    libtasn1-bin \
    libjson-perl \
    libpopt-dev \
    libssl-dev \
    iputils-ping \
    net-tools \
    traceroute \
    man \
    iproute2 \
    krb5-user \
    ldap-utils \
    gdb \
    bind9 \
    autoconf \
    libtool \
    gettext \
    gperf \
    autopoint \
    gtk-doc-tools \
    wget \
    autogen \
    libev4 \
    libev-dev \
    texinfo \
    lmdb-utils \
    dnsutils \
    python3-cryptography \
    python3-pyasn1 \
    python3-iso8601
