sudo yum install -y \
         words \
         ctags \
         clang \
         clang-devel \
         llvm-devel \
         gcc-c++ \
         cmake \
         cmake3 \
         bc \
         git \
         vim \
         tmux \
         tig \
         ansible \
         ack \
         man-pages \
         zlib-devel \
         openssl-devel \
         cowsay \
         fortune \
         figlet \
         perf \
         fontconfig \
         dos2unix \
         pandoc \
         rpm-build \
         python3 \
         lksctp-tools-devel \
         gtest-devel \
         oracle-instantclient12.1-devel
