sudo apt install -y \
    git \
    tmux \
    gcc \
    sudo \
    python3 \
    python3-dev \
    python3-dns \
    python3-dnspython \
    python3-jedi \
    python3-markdown \
    python3-cryptography \
    python3-pyasn1 \
    python3-iso8601 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    apt-file \
    build-essential \
    cmake \
    clang \
    libclang-14-dev \
    zlib1g-dev \
    libpcap-dev \
    libnuma-dev \
    libconfig++-dev \
    ninja-build \
    virtualenv \
    libspdlog-dev \
    doxygen \
    dnsutils \
    man \
    gdb \
    bear \
    tcpdump \
    dh-make \
    rsync \
    ragel \
    bc \
    gcovr \
    flex \
    bison \
    lcov \
    bind9 \
    gperf \
    lmdb-utils \
    linux-perf \
    autoconf \
    krb5-user \
    ldap-utils \
    libgnutls28-dev \
    liblmdb-dev \
    libgpgme11-dev \
    libparse-yapp-perl \
    libjansson-dev \
    libacl1-dev \
    libldap2-dev \
    libpam0g-dev \
    libdbus-1-dev \
    libtasn1-bin \
    libjson-perl \
    libpopt-dev \
    libssl-dev \
    libarchive-dev \
    libsystemd-dev \
    libncurses-dev \
    protobuf-compiler

# neovim
#pip3 install --upgrade meson
#pip3 install pyelftools
